version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  back:
    build:
      context: ./back
      dockerfile: Containerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Containerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - back

volumes:
  postgres_data:
